[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
ffi = true

[dependencies]
"@oasisprotocol-sapphire-foundry" = "0.1.2"
"@oasisprotocol-sapphire-contracts" = "0.2.15"

[rpc_endpoints]
sapphire-localnet = "http://localhost:8545"
sapphire-testnet = "https://testnet.sapphire.oasis.io"
sapphire = "https://sapphire.oasis.io"
